services:
  - type: web
    name: my-express-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    rootDir: server
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
